spring:
            datasource:
                        url: jdbc:mysql://127.0.0.1:3306/qs?useSSL=true&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
                        username: root
                        password: 1234

logging:
            level:
                        com:
                                    wjy: DEBUG